export const DEFAULT_SKILLs = [
  "html",
  "css",
  "js",
  "react",
  "node",
  "next",
  "express",
  "tailwind",
  "AWS",
  "Azure",
  "DevOps",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "Big Data",
  "Data Engineering",
];
// const DEFAULT_SKILLS = [
//   "html",
//   "css",
//   "js",
//   "react",
//   "node",
//   "next",
//   "express",
//   "tailwind",
  
//   "Google Cloud Platform",
//   "Blockchain",
//   "Artificial Intelligence (AI)",
//   "Machine Learning (ML)",
  
//   "Microservices",
//   "Serverless Computing",
 
//   "Data Science",
//   "Data Analytics",
//   "Security",
//   "Networking",
//   "Linux/Unix",
//   "Scripting (Python, Bash)",
//   "Database Management (SQL, NoSQL)",
//   "Version Control (Git)",
// ];
